python run_summarization.py \
    --model_name_or_path ../cnndm_t5_small_run2 \
    --do_cali True \
    --dataset_name cnn_dailymail \
    --dataset_config_name "3.0.0" \
    --output_dir ./save/cali \
    --per_device_eval_batch_size 1 \
    --deploy_scenario True \
    --use_synchronize True \
    --overwrite_output_dir \
    --predict_with_generate True \
    --source_prefix "summarize: " \
    --max_eval_samples 10 \
    --max_calibrate_samples 50 \
    --use_early_exit True \
    --exit_conf_type softmax \
    --exit_min_layer 1 \
    --calibrate_delta 10 \
    --calibrate_epsilon 0.05 \
    --consistency_type textual \
    --thresholds 1.0 0.9 0.8 0.7 0.6 \
    > outputs/output8.log 2>&1
